#include "gs_map_writer.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace gs_map_io {

namespace {

// 3DGS SH degree 3 = 16 (l,m) coefficient pairs x 3 RGB channels - 1 DC = 45
// f_rest_* floats. This writer emits f_rest_* = 0 because GS-LIVO's training
// loop only optimizes SH degree 0 (the paper's §II.B.2 explicitly initializes
// higher-order SH coefficients to zero). If a future revision computes higher
// SH, this constant stays -- only the zero-fill in dump_gs_map_to_ply changes.
constexpr int kShDegree = 3;
constexpr int kShCoeffsPerChannel = (kShDegree + 1) * (kShDegree + 1);  // 16
constexpr int kShRestFloats = 3 * (kShCoeffsPerChannel - 1);             // 45

constexpr int kFloatsPerInputVertex = 19;   // sizeof(GS_point) / sizeof(float)
constexpr int kFloatsPerOutputVertex = 6 + 3 + kShRestFloats + 1 + 3 + 4;  // 62

constexpr float kShC0 = 0.28209479177387814f;

inline float inverse_sigmoid(float x) {
  // Clamp into (eps, 1-eps) so the log doesn't blow up at the extremes.
  constexpr float eps = 1e-6f;
  if (x <= eps) x = eps;
  if (x >= 1.0f - eps) x = 1.0f - eps;
  return std::log(x / (1.0f - x));
}

}  // namespace

void dump_gs_map_to_ply(const std::filesystem::path& file_path,
                       const std::vector<GS_point>& gaussian_cloud) {
  const size_t N = gaussian_cloud.size();
  if (N == 0) {
    // Empty map -- still emit a syntactically valid (zero-vertex) PLY so
    // downstream rerun loaders don't choke. This is the "shutdown after a
    // very early exit" case.
  }

  std::filesystem::create_directories(file_path.parent_path());

  // Emit the ASCII PLY header to a small buffer first, then append the
  // little-endian binary payload. We don't use tinyply because lib3dgs's
  // CMakeLists.txt's `find_package(tinyply REQUIRED)` has no config file
  // installed on this vendored tree (another pre-existing vendoring gap);
  // a few hundred lines of plain std::ofstream is enough and removes that
  // dependency from the save path entirely.
  std::ofstream out(file_path, std::ios::out | std::ios::binary | std::ios::trunc);
  if (!out.is_open()) {
    throw std::runtime_error("gs_map_io::dump_gs_map_to_ply: failed to open " + file_path.string());
  }

  // Build the f_rest_* property names. PLY parsers expect them to be
  // contiguous and zero-indexed.
  std::string f_rest_props;
  f_rest_props.reserve(kShRestFloats * 14);  // ~"f_rest_NN " + comma
  for (int j = 0; j < kShRestFloats; ++j) {
    if (j > 0) f_rest_props.push_back(' ');
    f_rest_props += "f_rest_";
    if (j < 10) f_rest_props.push_back(static_cast<char>('0' + j));
    else {
      f_rest_props.push_back(static_cast<char>('0' + (j / 10)));
      f_rest_props.push_back(static_cast<char>('0' + (j % 10)));
    }
  }

  // Header. format binary_little_endian 1.0 is what every 3DGS viewer reads;
  // version 1.0 is the canonical PLY spec.
  out << "ply\n";
  out << "format binary_little_endian 1.0\n";
  out << "comment Generated by gs-livo (fork: Kyaw-Thiha/cerberus-GS-LIVO)\n";
  out << "element vertex " << N << "\n";
  out << "property float x\n";
  out << "property float y\n";
  out << "property float z\n";
  out << "property float nx\n";
  out << "property float ny\n";
  out << "property float nz\n";
  out << "property float f_dc_0\n";
  out << "property float f_dc_1\n";
  out << "property float f_dc_2\n";
  out << "property float " << f_rest_props << "\n";
  out << "property float opacity\n";
  out << "property float scale_0\n";
  out << "property float scale_1\n";
  out << "property float scale_2\n";
  out << "property float rot_0\n";
  out << "property float rot_1\n";
  out << "property float rot_2\n";
  out << "property float rot_3\n";
  out << "end_header\n";

  // Per-vertex binary payload. 62 floats per vertex, packed contiguously.
  // Allocate once and reuse -- avoids per-vertex heap traffic on multi-GB maps.
  std::vector<float> row(kFloatsPerOutputVertex);
  for (size_t i = 0; i < N; ++i) {
    const GS_point& p = gaussian_cloud[i];
    float* o = row.data();

    // xyz
    o[0] = p._points.x; o[1] = p._points.y; o[2] = p._points.z;
    // normal -- pass through whatever was stored (Dump_to_our_format zeros
    // this field; if a future revision tracks it, the value flows through)
    o[3] = p._normals.x; o[4] = p._normals.y; o[5] = p._normals.z;
    // f_dc -- SH degree 0 from RGB. SH2RGB round-trip = (f_dc * SH_C0) + 0.5
    o[6] = (p._colors.r - 0.5f) / kShC0;
    o[7] = (p._colors.g - 0.5f) / kShC0;
    o[8] = (p._colors.b - 0.5f) / kShC0;
    // f_rest_0..44 -- no higher-order SH in GS-LIVO's training loop
    for (int j = 0; j < kShRestFloats; ++j) o[9 + j] = 0.0f;
    // opacity -- inverse_sigmoid of the stored opacity (which is in [0,1]
    // and represents the "rendered" opacity, not the optimizer's logit)
    const size_t opacity_off = 9 + kShRestFloats;
    o[opacity_off] = inverse_sigmoid(p._opacity);
    // scale_0..2 -- _distance.r1/r2/r3. The GaussianModel stores exp(_scaling)
    // here, which IS the actual scale, so write it through as-is.
    const size_t scale_off = opacity_off + 1;
    o[scale_off + 0] = p._distance.r1;
    o[scale_off + 1] = p._distance.r2;
    o[scale_off + 2] = p._distance.r3;
    // rot_0..3 -- (qw, qx, qy, qz) in the 3DGS writer's convention.
    const size_t rot_off = scale_off + 3;
    o[rot_off + 0] = p._quaternion.qw;
    o[rot_off + 1] = p._quaternion.qx;
    o[rot_off + 2] = p._quaternion.qy;
    o[rot_off + 3] = p._quaternion.qz;

    out.write(reinterpret_cast<const char*>(row.data()),
              kFloatsPerOutputVertex * sizeof(float));
  }
  out.flush();
  if (out.fail()) {
    throw std::runtime_error("gs_map_io::dump_gs_map_to_ply: write failed for " + file_path.string());
  }
}

}  // namespace gs_map_io
